sudo: false
dist: trusty
language: node_js
node_js:
  - "6"
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - npm install -g grunt-cli
  # next 3 lines temporary until google-chrome-stable is 59+
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
